In [1]:
# Importing the necessary Python libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Getting the Iris dataset from Scikit-Learn
iris = datasets.load_iris()

# Loading the predictor value (y) and remainder of the training dataset (X) as Pandas DataFrames
X = pd.DataFrame(data = iris['data'], columns = iris['feature_names'])
y = pd.DataFrame(data = iris['target'], columns = ['target'])

# Performing a train_test_split on the dataset
X_train, X_val, y_train, y_val = train_test_split(X, y)

In [3]:
# Instantiating a RandomForestClassifier model
rfc_model = RandomForestClassifier(n_estimators = 50,
                                   max_depth = 20,
                                   min_samples_split = 5,
                                   min_samples_leaf = 2)

In [4]:
# Fitting the X_train and y_train datasets to the RandomForestClassifier model
rfc_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=50)

In [5]:
# Getting inferential predictions for the validation dataset
val_preds = rfc_model.predict(X_val)

# Generating validation metrics by comparing the inferential predictions (val_preds) to the actuals (y_val)
val_accuracy = accuracy_score(y_val, val_preds)
val_confusion_matrix = confusion_matrix(y_val, val_preds)

# Printing out the validation metrics
print(f'Accuracy Score: {val_accuracy}')
print(f'Confusion Matrix: \n{val_confusion_matrix}')

Accuracy Score: 0.9736842105263158
Confusion Matrix: 
[[15  0  0]
 [ 0 10  1]
 [ 0  0 12]]


In [6]:
# Instantiating another RandomForestClassifier object
other_rfc_model = RandomForestClassifier()

In [7]:
# Extracting attributes of the original trained model
target_classes = rfc_model.classes_
estimators = rfc_model.estimators_
n_classes = rfc_model.n_classes_
n_features = rfc_model.n_features_in_
feat_names = rfc_model.feature_names_in_
n_feats_out = rfc_model.n_outputs_
feat_importances = rfc_model.feature_importances_
params = rfc_model.get_params()

In [8]:
# Applying model attributes to new model object
other_rfc_model.set_params(**params)
other_rfc_model.classes_ = target_classes
other_rfc_model.estimators_ = estimators
other_rfc_model.n_classes_ = n_classes
other_rfc_model.n_features_in_ = n_features
other_rfc_model.feature_names_in_ = feat_names
other_rfc_model.n_outputs_ = n_feats_out

In [9]:
# Getting inferential predictions for the validation dataset
val_preds = other_rfc_model.predict(X_val)

# Generating validation metrics by comparing the inferential predictions (val_preds) to the actuals (y_val)
val_accuracy = accuracy_score(y_val, val_preds)
val_confusion_matrix = confusion_matrix(y_val, val_preds)

# Printing out the validation metrics
print(f'Accuracy Score: {val_accuracy}')
print(f'Confusion Matrix: \n{val_confusion_matrix}')

Accuracy Score: 0.9736842105263158
Confusion Matrix: 
[[15  0  0]
 [ 0 10  1]
 [ 0  0 12]]
